### ISSUE TITLE
Support for secondary-artifacts in codebuild_build.sh

### ISSUE THREAD

**Issue by PierreKiwi** [aws/aws-codebuild-docker-images#128]
Hello,
I started playing with local CodeBuild builds recently and it looks like the instruction `secondary-artifacts` is not honored.

buildspec.yml
```
version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/dir1
      - touch file1
      - cd $CODEBUILD_SRC_DIR/dir2
      - touch file2

artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR/dir1
      files:
        - file1
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR/dir2
      files:
        - file2
```

command
```./codebuild_build.sh -i aws/codebuild/python:3.6.5 -a codebuild_build```

output
```
...
agent_1  | [Container] 2018/10/11 20:41:57 Phase context status code: CLIENT_ERROR Message: no definition for primary artifacts in buildspec
agent_1  | [Container] 2018/10/11 20:41:57 Runtime error (*errors.errorString: no definition for primary artifacts in buildspec)
```

If I add a `files` section to `artifacts`, CodeBuild does the zipping of whatever it is specified but secondary artifacts are still not created.

**Comment by zabullet** [comment]
This looks like a bug, frankly. Using codeDeploy from console I get the same issue.

This format should be supported as per

https://docs.aws.amazon.com/codebuild/latest/userguide/sample-multi-in-out.html

**Comment by awszhen** [comment]
Hi! This is resolved in the latest version of the local agent. SHA: c2dacbc1091a274d587be349075dcec64e5890a58232ed7329c55bd972608a81

**Comment by vibhuyadav** [comment]
It is probably unrelated to local agent but I am having the same issue on AWS Codebuild when I only specify secondary artifacts.

![primaryartifactmissing](https://user-images.githubusercontent.com/6370789/49888325-bab09f00-fe0c-11e8-9e36-15d5063cbc4d.PNG)

**Comment by subinataws** [comment]
@vibhuyadav - could you please post that error message and the buildspec (remove any sensitive info) on CodeBuild's AWS forums (https://forums.aws.amazon.com/forum.jspa?forumID=230)? Oncalls will take a look.

**Comment by awszhen** [comment]
Hi @vibhuyadav , this is the expected behavior. Primary artifacts location is required in local agent. And you can not specify secondary artifacts unless you specify primary artifacts.

**Comment by vibhuyadav** [comment]
> Hi @vibhuyadav , this is the expected behavior. Primary artifacts location is required in local agent. And you can not specify secondary artifacts unless you specify primary artifacts.

@awszhen But this is AWS Codebuild and not local agent. I should post this in AWS forums including the buildspec. Thanks @subinataws

**Comment by shduke** [comment]
@vibhuyadav did you find a resolution to this? Or do you have a link to your forum post?

**Comment by dean-hsu** [comment]
Each artifact identifier under secondary-artifacts block in buildspec.yml must match an artifact defined in the secondaryArtifacts attribute of CodeBuild project.

**Comment by vibhuyadav** [comment]
@shduke I did not. For the sake of it I tried again using localbuild and I still see it.
Buildspec -
```
  post_build:
    commands:
      - echo Pre-Build Phase


artifacts:
  secondary-artifacts:
    bin:
      files:
        - deploy/**
      name: bin
      discard-paths: no
```

Error - 
```
agent_1  | [Container] 2019/07/22 20:19:19 Phase complete: UPLOAD_ARTIFACTS State: FAILED
agent_1  | [Container] 2019/07/22 20:19:19 Phase context status code: CLIENT_ERROR Message: no definition for primary artifacts in buildspec
agent_1  | [Container] 2019/07/22 20:19:19 Runtime error (*clienterr.PhaseContextError: no definition for primary artifacts in buildspec)
```

**Comment by solsglasses** [comment]
Bump, this is still a problem. Please re-open.  `codebuild_build.sh` is not matching CodeBuild in regards to `secondary-artifacts` config

**Comment by edalongeville** [comment]
This is still happening. Could this issue be reopened please ?

**Comment by ShaneGH** [comment]
Could be because you are using "secondary-artifacts" instead of "secondary_artifacts".
The documentation is confusing as to the naming conventions

**Comment by kti-chris** [comment]
This is due to a bad example in the documentation. This will NOT work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

The issue is documented here: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

artifacts/files
**Required sequence**. Represents the locations that contain the build output artifacts in the build environment. Contains a sequence of scalars, with each scalar representing a separate location where CodeBuild can find build output artifacts, relative to the original build location or, if set, the base directory.

So this is an edited version that does work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  files:
    - directory/*
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

**Comment by ioMatrix** [comment]
This is due to a bad example in the documentation. This will NOT work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

The documentation, obscurely, points it out: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

artifacts/files
**Required sequence**. Represents the locations that contain the build output artifacts in the build environment. Contains a sequence of scalars, with each scalar representing a separate location where CodeBuild can find build output artifacts, relative to the original build location or, if set, the base directory.

So this is an edited version that does work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  files:
    - directory/*
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```
