### ISSUE TITLE
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI not provided for Local CodeBuild

### ISSUE THREAD

**Issue by joekiller** [aws/aws-codebuild-docker-images#179]
We have several builds that pass the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable per [Troubleshooting CodeBuild Error: "Unable to Locate Credentials"](https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-versions)

So when we try the following AWS_CONTAINER_CREDENTIALS_RELATIVE_URI isn't in the environment so I cannot test these builds locally.

> docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t your-image-tag .

Can you all update the local build to provide this service?

**Comment by subinataws** [comment]
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is  only available within the context of CodeBuild on AWS cloud. How are you using environment variable within your builds? How does it effect your local builds? A buildspec sample would be great.

**Comment by joekiller** [comment]
Our primary use case pretty much exactly what is outlined in the _Troubleshooting CodeBuild Error: "Unable to Locate Credentials"_ link I posted prior. We pass the IAM role of the build to our docker image being built or run. The docker image maybe creating an artifact or be the artifact itself.

For example the role is used for to resolve python pip requirements.txt entries like `git+https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-awesome-project@master#egg=my-awesome-project` which relies on the [CodeCommit AWS CLI Credential Helper](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html) to access the repository.

Another way the role is used is via [s3-wagon-private](https://github.com/s3-wagon-private/s3-wagon-private) which allows maven dependencies to live on s3 buckets and the dependency tool resolves permissions via the IAM role.

Currently Local CodeBuild lets me use the `-c` switch which works fine for enabling a "role" for code running in the build space itself but not if we want to run our docker builds with an IAM/credential enabled environment.

A typical buildspec is:

```
version: 0.2

env:
  variables:
    FN_NAME: "my-awesome-function"

phases:
  install:
    commands:
      - mkdir -p target
      - printenv >> target/metadata
  build:
    commands:
      - docker build -t ${FN_NAME} .
      - docker run -e AWS_REGION=${AWS_REGION} -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI} -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} -v $(pwd)/target:/tmp/target ${FN_NAME}

artifacts:
  files:
    - '**/*'
  base-directory: target

```
or
```
version: 0.2

env:
  variables:
    FN_NAME: "my-awesome-function"

phases:
  install:
    commands:
      - mkdir -p target
      - printenv >> target/metadata
  build:
    commands:
      - docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t ${FN_NAME} .
      - docker run -v $(pwd)/target:/tmp/target ${FN_NAME} cp /opt/artifact.zip /tmp/target/

artifacts:
  files:
    - '**/*'
  base-directory: target
```

Ideally if I pass `-c` to CodeBuild Local then `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` has a little service that passes the "role" along.
