### ISSUE TITLE
Ubuntu 14.04 support ended. Any update (docker)

### ISSUE THREAD

**Issue by michaltajchertdev** [aws/aws-codebuild-docker-images#198]
Ubuntu 14.04 just ended his life.
https://wiki.ubuntu.com/Releases

Your docker, PHP, java... images based on this version.

The problem for me is I can't install PHP 7
https://www.patreon.com/posts/ubuntu-14-04-php-22093917

I can't use 'ubuntu/standard/2.0' because of this error in CodeBuild:
`Phase context status code: YAML_FILE_ERROR Message: This build image requires selecting at least one runtime version.`

Will you update Ubuntu version on docker or PHP images? When?

**Comment by taupecat** [comment]
+1

**Comment by subinataws** [comment]
When using the "aws/codebuild/standard:2.0" CodeBuild managed image, you will need to specify a "runtime-versions". Buildspec syntax @ https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax.

A sample buildspec for PHP would look like:

```
version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
  build:
    commands:
      - php --version
artifacts:
  files:
    -  README.md
```
