### ISSUE TITLE
Unable to run Laravel Dusk tests

### ISSUE THREAD

**Issue by ibarrajo** [aws/aws-codebuild-docker-images#245]
Laravel Dusk is a browser testing tool that uses chrome driver and chromium to run tests.

My buildspec looks like so:

```
version: 0.2

env:
  variables:
     AWS_DEFAULT_REGION: "us-west-2"
     AWS_ACCOUNT_ID: "<redacted>"
     IMAGE_REPO_NAME: "<redacted>"
     IMAGE_TAG: "latest"
     APP_ENV: "testing"
phases:
  install:
    runtime-versions:
      docker: 18
      # name: version 
    commands:
     - export LC_ALL="en_US.UTF-8"
     - locale-gen en_US en_US.UTF-8
     - dpkg-reconfigure locales
     #- apt-get install kmod -y 
     #- modprobe br_netfilter
     - |
      mkdir -p /etc/docker && echo '{"debug" : true, "experimental" : false, "ipv6": true, "fixed-cidr-v6": "2600:1f18:47b:ca03::8/126"}' > /etc/docker/daemon.json;
      echo "net.bridge.bridge-nf-call-iptables = 1\n" >> /etc/sysctl.conf;
      echo "net.bridge.bridge-nf-call-ip6tables = 1\n" >> /etc/sysctl.conf;
     #- sysctl -p
     - nohup  /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --config-file=/etc/docker/daemon.json&
     - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
```

The actual unit tests run within the container when the docker image is being built. The docker image being built is based on `php:7.3-fpm-alpine` where `chromium` and `chromium-chromedriver` are used by Dusk to run the browser tests.

The very weird issue is that the unit tests run within the docker image sucessfully in multiple other environments. But they don't work within the docker daemon provided by the codebuild 2.0 docker image. It looks like the Chrome starts up but just dumps an empty page. I checked out the differences between `docker info` of environments that work and codebuild.

The main difference was in these warnings I got when running `docker info`
```
WARNING: bridge-nf-call-iptables is disabled 
WARNING: bridge-nf-call-ip6tables is disabled 
```

As you can see from the buildspec file, I'm enabling ipv6 since it's a requirement for chromium to even start. But in the commented-out portions I'm also installing kmod so I can load br_netfilter with `modprobe br_netfilter`. It fails because it's something that needs to be provided by the hosting kernel. I found a bunch of related issues touching on this and it seems to point to a Linux Kernel issue that was patched in kernel 5.3

https://lkml.org/lkml/2019/6/6/434
https://bugs.chromium.org/p/chromium/issues/detail?id=878034
The kernel patch: https://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf-next.git/commit/?id=22567590b2e634247931b3d2351384ba45720ebe

I wish to keep using the images provided by CodeBuild if possible, do you guys have any recommendations?

I think it will be a long time until there is a codebuild 3.0 image with linux kernel 5.3
