### ISSUE TITLE
-e flag has no effect

### ISSUE THREAD

**Issue by detectedstealth** [aws/aws-codebuild-docker-images#247]
Trying to run the following command and none of the environment variables in the specified file are actually being included in the buildspec.yml

```
./scripts/codebuild_build.sh -i ubuntu-standard-2.0 -a ./artifacts -c ~/.aws -e local.evn -s .
```

Contents of the local.evn (in the same directly as I'm running the command from)
```
AWS_DEFAULT_REGION=us-west-2
REPOSITORY_URI=AWSID.dkr.ecr.us-west-2.amazonaws.com/REPO
```

Not sure what I'm doing wrong at this point. No errors related to not finding the file are displayed the only thing related to the variables I'm seeing is:

```
[Container] 2019/08/28 07:50:33 Processing environment variables
```

Also here is my Buildspec.yml
```
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - echo $REPOSITORY_URI
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -f dockerfiles/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
```
