### ISSUE TITLE
Nodejs 12.14 and 13.x Support

### ISSUE THREAD

**Issue by FYJen** [aws/aws-codebuild-docker-images#311]
The support for Nodejs runtime version 12.14+ and 13.x will be very useful.

Use case:
- JavaScript test runner: https://github.com/avajs/ava
- Required Nodejs engine: `>=10.18.0 <11 || >=12.14.0 <13 || >=13.5.0`
- AVA version: `3.5`

Current work around:
- Downgrade AVA version to `2.4.0` which supports `12.13`

I am happy to learn if anyone has done Nodejs upgrade in the default codeBuild image.

**Comment by subinataws** [comment]
@FYJen - CodeBuild images do have "n" installed on them. So you can do "n latest" or "n 12.16.1", etc. Note that 13.x isn't LTS and we only plan to support LTS version of the runtime versions on CodeBuild images.

```
version: 0.2

phases:
  build:
    commands:
      - node -v
      - n latest
      - node -v
      - n 12.16.1
```
