### ISSUE TITLE
Upgrade AWS cli to the latest version

### ISSUE THREAD

**Issue by ruanltbg** [aws/aws-codebuild-docker-images#313]
The Amazon CLI is on the version 2.0.3  https://github.com/aws/aws-cli/releases but on the containers, it is set on a very old version: 

```
aws-cli/1.16.284 Python/3.6.8 Linux/4.14.152-98.182.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.13.20
```

**Comment by subinataws** [comment]
@ruanltbg - aws-cli release every couple of days. CodeBuild image version will also be a few versions older. We have a release in flight, which will update to aws-cli/1.18, which was released roughly 12 days ago.

Our suggestion would be to update the aws-cli inside the build container, if you are relying on a new feature that is supported only in the latest version.

**Comment by ruanltbg** [comment]
Ok, no problem. Thank you @subinataws

**Comment by atheiman** [comment]
What would be the codebuild config to automatically update aws cli at the start of a build? Using codebuild image `aws/codebuild/standard:5.0`

**Comment by teuber789** [comment]
@atheiman I was able to get it to work with these commands:

```yaml
version: 0.2

phases:

  pre_build:
    commands:
      # Install the AWS CLI V2.
      # This doesn't remove AWS CLI V1, it just puts V2 before
      # V1 on the path so that V2 is found first. V1 can still be
      # accessed at /root/.pyenv/shims/aws.
      - sudo mkdir /usr/local/awscliv2
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - >
        sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/awscliv2 --update
      - export PATH="/usr/local/bin:$PATH"

  build:
    commands:
      # Should be aws-cli/2.x
      - aws --version
      # <more commands here>
```

I am using `aws/codebuild/amazonlinux2-x86_64-standard:3.0`, but I imagine it would be similar for `standard:5.0`.
