### ISSUE TITLE
Problem to connect postgres instance in local CodeBuild

### ISSUE THREAD

**Issue by Insidexa** [aws/aws-codebuild-docker-images#326]
I have `buildspec.yml`  
```
version: 0.2

phases:
  install:
    commands:
      - docker pull postgres
  pre_build:
    commands:
      - docker run -p 5432:5432 --name sample-postgres -e POSTGRES_PASSWORD=sample -e POSTGRES_USER=sample -e POSTGRES_DB=sample -d postgres >> container.txt
  build:
    commands:  
      - sleep 20s
      - apt-get install -y telnet iproute2 net-tools
      - docker inspect sample-postgres >> container.txt
      - ip addr show >> container.txt
      - route >> container.txt
      - npm i --save pg
      - node index.js  >> container.txt
  post_build:
    commands:
      - docker rm -f sample-postgres
artifacts:
  files:
    - container.txt
```

Postgres already created and running.  
Postgres connection string:  
`postgresql://sample:sample@127.0.0.1:5432/sample`

Can`t connect to postgres in CodeBuild. I got next error:  
```
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
```

Docker inspect command of sample-postgres
```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "bf27197fe81dc940a55351c128c87022a963261b9528e5c38f35fad70d1a1c77",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5432/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5432"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/bf27197fe81d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "95c48a5070ccd6475292c259bcde4514174f3ff3b042a2d54dcde50b0e80ea3a",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "930c686de17cc1c7eed52251f1c860c3564b8b34348fea6c3906d8e9436778a3",
                    "EndpointID": "95c48a5070ccd6475292c259bcde4514174f3ff3b042a2d54dcde50b0e80ea3a",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null
                }
            }
        }
```

I trying connect with telnet in `buildspec.yml` to database container `sample-postgres` with  `IPGateway`, `IPAddress` and got error  connection refused

**Comment by xinw0911** [comment]
Hello,
I tried with adding the following commands to the build spec.
- ipAddress=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' sample-postgres`
- telnet $ipAddress 5432
I have the following response in my log:

Trying 172.18.0.2...
--
Connected to 172.18.0.2.
Escape character is '^]'.

Seems like it works.
Could you try it out and see if it works or not?

Thanks!
Xin

**Comment by Insidexa** [comment]
@xinw0911, thanks for the answer

```
[Container] 2020/03/25 06:45:51 Running command ipAddress=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' sample-postgres)

[Container] 2020/03/25 06:45:51 Running command telnet $ipAddress 5432
telnet: Unable to connect to remote host: Connection timed out
Trying 172.17.0.3...
```

**Comment by Insidexa** [comment]
But it works in AWS CodeBuild ( non local )

**Comment by joni-** [comment]
@Insidexa are you running OSX? I wasn't able to connect to postgres either until I changed host to host.docker.internal. https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

**Comment by Insidexa** [comment]
@joni- I am not using OSX, I use Fedora 32

**Comment by ThrowsException** [comment]
Ive run into the same issue. Using docker-compose to bring up containers and connect to them does not work using 'localhost' in the local runner but found that it works fine in the actual codebuild project. minimal reproducible example here https://github.com/ThrowsException/aws-docker-in-docker just doing a simple curl from the script to a running nginx container.

**Comment by yasas-mintpay** [comment]
any update on this?. What to use insted of localhost?

**Comment by awilkins** [comment]
Suspect this is another expression of the problem addressed here :

https://github.com/aws/aws-codebuild-docker-images/issues/548

Or : "My build depends on external services, I would like to run instances of those locally as well as my build"

Poking about in the `aws-codebuild-local` image the way it works is by raising a docker stack using compose and waiting for it to terminate. You can find the `docker-compose` file for this stack at /LocalBuild/agent-resources inside the image.

This compose file has no declarations of a network (or any way to inject one). It would be nice to do this explicitly (to e.g. simulate the placement of your build container in a specific VPC which CodePipeline can do).

Hackaround : 

Because this stack is always what runs your build, and always runs from this folder inside the container, and doesn't declare a specific network, it has a predictable network name of `agent-resources_default`

If you place your simulated stack in this network, your build machine can route packets to it.

e.g.

```yaml
networks:
  build_infrastructure:
    name: agent-resources_default
    external: true  # this tells docker the network doesn't belong to this stack

services:
  hello:
    image: python
    command: "python -m http.server"
    networks:
      - build_infrastructure
    ports:
      - published: 8000
        target: 8000
```

and the buildspec

```yaml
version: 0.2

phases:
  build:
    commands:
      - curl http://hello:8000
```

There is a mild chicken/egg problem here in that the network belongs to the CodeBuild agent and not your infra stack, but your infra stack won't start without the network existing, but the CodeBuild stack won't start if the network name is occupied and not created by a compose project withthe same name (it checks the network labels).

The hackaround for this is to add this and `up`  it first ; the `hello-world` container terminates fast leaving the network standing. CodeBuild local will accept this network as it's own, and your infra stack will have no problem attaching to it.

```
# in agent-resources/docker-compose.yml
networks:
  default:

services:
  network:
    image: hello-world
    networks:
      - default
```

The non-cheesy way to do all this is to extend the `docker-compose.yml` files inside the codebuild container with your own that contain the infra stack you wish to simulate - that requires you to copy out the files, edit them, and specify a different agent image with the `-l` parameter.
