### ISSUE TITLE
ImportError: libpython3.7m.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by burritoIand** [aws/aws-codebuild-docker-images#329]
Hello, I just started getting failing builds in my ci/cd with codebuild using standard 2.0 (tried 3.0 too). It's a python3.7 app
```
ve/lib/python3.7/site-packages/api/v1/aws.py:11: in <module>
    from awscrt import auth, io, mqtt
ve/lib/python3.7/site-packages/awscrt/auth.py:15: in <module>
    import _awscrt
E   ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

```
  AppCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: 'CODEPIPELINE'
      Cache:
        Location: !Ref BuildCacheBucket
        Type: 'S3'
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        EnvironmentVariables:
          - Name: 'ARTIFACT_BUCKET'
            Value: !Ref ArtifactStoreBucket
        Image: 'aws/codebuild/standard:2.0'
        Type: 'LINUX_CONTAINER'
      Name: !Sub '${AWS::StackName}-App-Codebuild'
      ServiceRole: !GetAtt CodebuildRole.Arn
      Source:
        Type: 'CODEPIPELINE'
      TimeoutInMinutes: 15
```
also tried standard 3.0 and  `Image: 'aws/codebuild/amazonlinux2-x86_64-standard:2.0'` (and 3)

```
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - virtualenv --python=python3.7 ve
  build:
    commands: ...
```
