### ISSUE TITLE
Support for test reporting and graceful error handling for unsupported features

### ISSUE THREAD

**Issue by StefanSmith** [aws/aws-codebuild-docker-images#337]
When using the latest version of `amazon/aws-codebuild-local` (DIGEST:sha256:bd69dbcdc9b3da66fd93de0b6d45534086367d6b48d3536d0248a01a459fb7e4), if my buildspec contains test reporting configuration, as defined [here](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#reports-buildspec-file), the build fails with a message such as:

```
agent_1  | [Container] 2020/04/17 09:08:17 Runtime error (*errors.errorString: arn: invalid prefix)
```

I get the same error whether I use a test report name:

```
reports:
  Tests:
    files:
      - application/smoke-tests/out/*.xml
```
Or a full arn:

```
reports:
  reports:
  arn:aws:codebuild:eu-west-1:*********:report-group/ApplicationTest-Tests:
    files:
      - application/smoke-tests/out/*.xml:
```
