### ISSUE TITLE
Support for nodejs version 14

### ISSUE THREAD

**Issue by ivanmartos** [aws/aws-codebuild-docker-images#361]
Current version of nodejs is 14 (https://nodejs.org/en/)

Could we pls get support of this version in `amazonlinux2*` image pls?

**Comment by subinataws** [comment]
@ivanmartos - We'll support nodejs version 14 once it is LTS. As per https://nodejs.org/en/about/releases/, that would be after 10/20. You can use "n latest" or "n 14" in your buildspec to get nodejs 14 within CodeBuild provided image.

**Comment by salimhamed** [comment]
@subinataws I'm not following your comment about `n latest` or `n 14`. Here's an example `buildspec.yml`:

```yaml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  # are you saying we can indicate to use node 14 here?
```

Also, in addition to `amazonlinux2*` images, can you please make `node 14` available in `aws/codebuild/standard:3.0` and `aws/codebuild/standard:4.0`?

**Comment by subinataws** [comment]
@salimhamed - No, not in runtimes section, but in your build commands. Node.js was LTS today. Team will add that to the new/latest CodeBuild images with its next rollout.

```
version: 0.2

phases:
  build:
    commands:
      - n latest
```
