### ISSUE TITLE
Image Doesn't have support for dotnet: 2.2

### ISSUE THREAD

**Issue by CLakshmi** [aws/aws-codebuild-docker-images#368]
https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/1.0/runtimes.yml 
  dotnet:
    versions:
      2.2:
        commands:
          - echo "Installing .NET version 2.2 ..."

But getting the below error during build for dotnet core 2.2 version 

7 | [Container] 2020/07/08 10:44:55 Selecting 'dotnet' runtime version '2.2' based on manual selections...
8 | [Container] 2020/07/08 10:44:55 Phase complete: DOWNLOAD_SOURCE State: FAILED
9 | [Container] 2020/07/08 10:44:55 Phase context status code: YAML_FILE_**ERROR Message: Unknown runtime named 'dotnet'. This build image has the following runtimes: docker, golang, java, nodejs, php, python, ruby**

**Comment by awszhen** [comment]
@CLakshmi , I can not reproduce this issue for `aws/codebuild/amazonlinux2-x86_64-standard:1.0` on my end. 
This is the buildspec file I used:

```yaml
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - dotnet --info
```
