### ISSUE TITLE
Confusing message showing "Using Docker 19" for both 18 and 19

### ISSUE THREAD

**Issue by djeppson** [aws/aws-codebuild-docker-images#387]
In our old buildspec.yml we have the since-deprecated request to run Docker 18 ... 
```yaml
install:
    runtime-versions:
      docker: 18
```

Until we can get that removed, we're still seeing this contradictory pair of log messages:
* `[Container] 2020/09/02 21:42:29 Selecting 'docker' runtime version '18' based on manual selections...`
    * Not sure what "manual selections" this is referring to
* `[Container] 2020/09/02 21:42:29 Running command echo "Using Docker 19"`

Lines 110-117 of https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/runtimes.yml:
```yaml
  docker:
    versions:
      18:
        commands:
          - echo "Using Docker 19"
      19:
        commands:
          - echo "Using Docker 19"
```
