### ISSUE TITLE
Difficulties to install miniconda properly

### ISSUE THREAD

**Issue by gandroz** [aws/aws-codebuild-docker-images#389]
I've got this buildspec

```
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - export PATH=/opt/conda/bin:$PATH  # should not be mandatory, but needed to call `conda` command
      - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      - sh ~/miniconda.sh -b -p /opt/conda
      - rm ~/miniconda.sh
      - ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
      - echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
      - echo "conda activate" >> ~/.bashrc



  pre_build:
    commands:
      # Initialize Conda for the current shell
      - conda init bash
      # Restart shell for changes to take effect. Does not seem to work :(
      - exec $SHELL
      - conda create -n myenv python=3.6
      # command `conda activate myenv` does not work, call `activate` the standard way
      - . activate myenv && which python  # returns /opt/conda/bin/python instead of /opt/conda/envs/myenv/bin/python
```

Conda is well installed but I have trouble to make it work properly. As stated in the doc, conda need to be initialized. However, the shell needs to be restarted afterwards, and the `exec $SHELL` does not seems to do it as I am not able to activate the virtual environment with `conda activate myenv`. Although, once activated (or I think it was), the python binary called is the one on the root, not the virtual environment.
