### ISSUE TITLE
Docker alpine build fails with Error 127 (/bin/sh: Operation not permitted) / Support Docker Engine v20.10.x

### ISSUE THREAD

**Issue by viktorhaid** [aws/aws-codebuild-docker-images#467]
We are using the base image `php:7.4-fpm-alpine` to `docker build` our app in CodeBuild.
With Alpine release v3.14 `make` commands fail with Error 127:
`make: /bin/sh: Operation not permitted`

Digging into it we found other issues referencing the same problem:
- https://github.com/alpinelinux/docker-alpine/issues/146
- https://github.com/igbinary/igbinary/issues/333 

With Alpine 3.14 `faccessat2` syscall has been enabled in musl. The release notes state that it needs to have at least Docker Engine v20.10.0 to work properly:
- https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

Both CodeBuild Images (`aws/codebuild/standard:4.0` + `aws/codebuild/standard:5.0`) come with Docker version 19.03.x.
Are there plans upgrading the docker runtime to 20.10?

**Comment by KernCheh** [comment]
Unfortunately, I've encountered a very similar issue with alpine images and `/bin/sh`

For now, referring to https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile#L362, a workaround with the `pre_build` hook in buildspec.yml
```yaml
phases:
  pre_build:
    commands:
      # Install docker 20
      - export DOCKER_VERSION="20.10.7"
      - DOCKER_BUCKET="download.docker.com"
      - DOCKER_CHANNEL="stable"
      - DOCKER_SHA256="34ad50146fce29b28e5115a1e8510dd5232459c9a4a9f28f65909f92cca314d9"
      - curl -fSL "https://${DOCKER_BUCKET}/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz
      - echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c -
      - tar --extract --file docker.tgz --strip-components 1  --directory /usr/local/bin/
      - rm docker.tgz
      - docker -v
```

Hope it helps!
