### ISSUE TITLE
.Net 6 runtime

### ISSUE THREAD

**Issue by darrenlewis1985** [aws/aws-codebuild-docker-images#497]
.Net 6 was recently released. When will this be supported in the standard images as a runtime version?

**Comment by humayunkhan2019** [comment]
+1

**Comment by mohananukalasf** [comment]
+1

**Comment by mbp** [comment]
Until we get official support for .NET 6, I want to share that in order to get it working, you can put the following command in your buildspec:

```
/usr/local/bin/dotnet-install.sh --channel LTS
```

This worked for me when using the `aws/codebuild/standard:5.0` image.

**Comment by Ratomir** [comment]
+1

**Comment by JarvisPos** [comment]
> .NET 6 için resmi destek alana kadar, çalışmasını sağlamak için yapınıza aşağıdaki komutu koyabileceğinizi paylaşmak istiyorum:
> 
> ```
> /usr/local/bin/dotnet-install.sh --channel LTS
> ```
> 
> Bu görüntüyü kullanırken bende işe yaradı.`aws/codebuild/standard:5.0`

can you share a code sample?

**Comment by brantsrasmus** [comment]
@JarvisPos 

Replace
```
phases:   
  install:
    runtime-versions:
      dotnet: latest
```
with
```
phases:   
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
```
