### ISSUE TITLE
pyenv: version `3.8.2' is not installed

### ISSUE THREAD

**Issue by hoIIer** [aws/aws-codebuild-docker-images#513]
**Describe the bug**
My codebuild project began to fail when I upgraded from `aws/codebuild/standard:3.0` to `aws/codebuild/standard:5.0` with the following error log:
```
[Container] 2022/03/15 21:36:58 Running command virtualenv --python=python3.8 ve
--
27 | pyenv: version `3.8.2' is not installed (set by /codebuild/output/src859025965/src/.python-version)
```

** Cloudformation
```
  IntegrationTestsCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: 'CODEPIPELINE'
      Cache:
        Location: !Ref BuildCacheBucket
        Type: 'S3'
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/standard:5.0'
        Type: 'LINUX_CONTAINER'
      Name: !Sub '${AWS::StackName}-Integration-Test'
      ServiceRole: !GetAtt CodebuildRole.Arn
      Source:
        Type: 'CODEPIPELINE'
      TimeoutInMinutes: 15
```

** buildspec.yml
```
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - virtualenv --python=python3.8 ve
```

**Expected behavior**
python 3.8 works as expected and my project runs, pytest works
