### ISSUE TITLE
Unable to run apt-get update on aws/codebuild/standard:4.0 or aws/codebuild/standard:5.0 ubuntu images. java-1.8.0-amazon-corretto-jdk:amd64 issues

### ISSUE THREAD

**Issue by mawaldne** [aws/aws-codebuild-docker-images#523]
Hello, I am trying to run apt-get update and its failing with: 

```
...
[Container] 2022/04/21 20:51:10 Running command apt-get update && apt-get upgrade ca-certificates -y
...
Errors were encountered while processing:
java-1.8.0-amazon-corretto-jdk:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

My buildspec config is pretty simple:

```
...
phases:
  pre_build:
    commands:
      - echo Prep started on `date`
      - docker login ...
      - docker run ...
      - apt-get update && apt-get upgrade ca-certificates -y
      - curl -sLv https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install --quiet 
....

```
I have tried both the aws/codebuild/standard:4.0 and aws/codebuild/standard:5.0 ubuntu images on latest. The last successful build was about a week ago. So this just started showing up today. I haven't seen anything about `java-1.8.0-amazon-corretto-jdk:amd64` in our previous builds. So something new is definitely happening there.
