### ISSUE TITLE
amazon-corretto development kit

### ISSUE THREAD

**Issue by MrSakhs** [aws/aws-codebuild-docker-images#567]
Requesting to have `Amazon Corretto 17 development tools` be installed available on the docker images. 

Currently the package `java-17-amazon-corretto-devel` has to be installed using buildspec file to have `javac` command available.

```
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - yum info java-17-amazon-corretto
      - yum info java-17-amazon-corretto-devel
      - yum -y install java-17-amazon-corretto-devel  
  build:
    commands:
      - which javac
      - javac -version
      - ls -l $JAVA_HOME/bin/
  ```
