### ISSUE TITLE
Docker daemon is not running on Custom image - even if Privileged mode = true is set

### ISSUE THREAD

**Issue by anhhq-1753** [aws/aws-codebuild-docker-images#568]
Hi, I'am using docker ubuntu 5.0 image. I tweaked the Ruby version a bit and rebuilt the image. I push that image to ECR and setting in Codebuild. But when I build, I get this error:
I have enabled Privileged mode in Environment.
![image](https://user-images.githubusercontent.com/58063202/194871536-4195860c-84d9-4afe-bdd4-4657bc1910a1.png)
Please let me know if I'm wrong somewhere.
```
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
--
716 | Configure a credential helper to remove this warning. See
717 | https://docs.docker.com/engine/reference/commandline/login/#credentials-store
718 |  
719 | Login Succeeded
720 | Building docker image. Please wait...
721 | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?```

**Comment by edeustace** [comment]
Same here with `public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0`. I have a Dockerfile that is based on that, push to ECR, then use it as the image for a CodeBuild project. But docker won't run. If I run the same project with al2 standard 4.0 - docker is running.

I've tried to re-set the `ENTRYPOINT` in my own docker file. Anything else I can try?

**Comment by subinataws** [comment]
@anhhq-1753 @edeustace - When you use docker image, that is not pre-baked and made available by the CodeBuild service itself, it is considered a custom image. In addition to setting the privileged flag, you will need to add the following commands (the one under install phase) to start docker inside your build container. This is briefly explained in https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html#sample-docker-custom-image-files

```
version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker info
```
