### ISSUE TITLE
Add support for Node 18

### ISSUE THREAD

**Issue by antonyfrancis** [aws/aws-codebuild-docker-images#580]
Hello there 👋 ,

Now that Node 18 is LTS, can we add support for Node 18 as a supported runtime on CodeBuild?

Thanks heaps.

**Comment by HaaLeo** [comment]
As described in [#490](https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-976470059) the following workaround also applies for nodejs 18:
```yaml
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
```
