### ISSUE TITLE
Can we have latest docker so that we can use multi-stage dockerfile?

### ISSUE THREAD

**Issue by rui-ktei** [aws/aws-codebuild-docker-images#6]
Hi, I'm a heavy AWS user who leverages the power of CodeBuild.

As per subject, I really wanna use multi-stage docker build feature:

https://docs.docker.com/engine/userguide/eng-image/multistage-build/

Is there any update possible that can let me use this feature?

Thanks a lot!

**Comment by dhilsand** [comment]
Thank you for your feedback and feature request. We've noted the request and will prioritize an updated version of Docker in the next release cycle of our curated images.

**Comment by rui-infotrack** [comment]
Hi, do we habe any update on this issue? Would we be expecting a release date soon?

Thank you

**Comment by subinataws** [comment]
Thanks for your patience. This issue continues to be on our backlog. However, we don't have an ETA.

**Comment by dipper-github** [comment]
You can use a custom docker image to unblock yourself. 
https://hub.docker.com/r/library/docker/ You can use the one that has the tag 'dind' (eg docker:17.06-dind)

**Comment by awsnitin** [comment]
You can use a custom docker image to unblock yourself.
https://hub.docker.com/_/docker/ Use the one that has the tag 'dind' (eg. 17.06-dind)

Sample: http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html

**Comment by orzarchi** [comment]
Is there any way to make use of docker's layer caching mechanism to speed up builds when using this technique?

**Comment by maxwellimpact** [comment]
I would also love to see a newer version of Docker for this exact same reason. I started an issue today and then saw this one. I'm closing mine in favor of promoting this. 👍

**Comment by maxwellimpact** [comment]
This took a few frustrating bouts, but I finally figured out how to use the latest version of Docker with CodeBuild and without having to build/maintain my own image. First do like @awsnitin said and use `dind` tag. In my case I'm using `docker:stable-dind`.

The gotcha is in both installing the awscli and getting the docker daemon running. Because AWS is taking over the entrypoint you will need to run it manually and then wait for it. Below is my pre-build step that should work fine for others.

```yaml
  pre_build:
    commands:
      - dockerd-entrypoint.sh &
      - |
        until docker info >/dev/null 2>&1
        do
        	sleep 1
        done
      - apk -Uuv add groff less python py-pip && pip install awscli
      - $(aws ecr get-login --no-include-email)
```

**Comment by rubyisbeautiful** [comment]
This is cool thanks @maxwellimpact.  I [created a PR](https://github.com/aws/aws-codebuild-docker-images/pull/22) before I saw this...I still can't get it to work without CodeBuild running the container with privileges.

**Comment by maxwellimpact** [comment]
@rubyisbeautiful sorry, forgot to mention that privileged mode is required for custom images that build an image with Docker (at least from what I've read in the docs). This is an option in CodeBuild, here is a snippet of my CloudFormation for my CodeBuild project.

```yaml
      Environment:
        ComputeType: "BUILD_GENERAL1_MEDIUM"
        Image: "docker:stable-dind"
        Type: "LINUX_CONTAINER"
        PrivilegedMode: true
```

You should be able to turn on privileged mode and have no issues, unless there is something more complicated with what/how you are building your image.
