### ISSUE TITLE
Unable to install Go 1.20

### ISSUE THREAD

**Issue by driverpt** [aws/aws-codebuild-docker-images#618]
**Describe the bug**
Be able to install latest go version

**To Reproduce**
1. `docker pull public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0`
2. `docker run --rm --entrypoint "" -it public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0 /bin/bash`
3. `goenv install 1.20`

**Expected behavior**
To be able to install latest Go Version via `goenv`

**Logs**
```
bash-4.2# goenv install 1.20.2
go-build: definition not found: 1.20.2

See all available versions with 'goenv install --list'.

If the version you need is missing, try upgrading goenv:

  cd /root/.goenv/plugins/go-build/../.. && git pull && cd -
```
```
bash-4.2# goenv install -l
Available versions:
  1.2.2
  1.3.0
  1.3.1
  1.3.2
  1.3.3
  1.4.0
  1.4.1
  1.4.2
  1.4.3
  1.5.0
  1.5.1
  1.5.2
  1.5.3
  1.5.4
  1.6.0
  1.6.1
  1.6.2
  1.6.3
  1.6.4
  1.7.0
  1.7.1
  1.7.3
  1.7.4
  1.7.5
  1.8.0
  1.8.1
  1.8.3
  1.8.4
  1.8.5
  1.8.7
  1.9.0
  1.9.1
  1.9.2
  1.9.3
  1.9.4
  1.9.5
  1.9.6
  1.9.7
  1.10.0
  1.10beta2
  1.10rc1
  1.10rc2
  1.10.1
  1.10.2
  1.10.3
  1.10.4
  1.10.5
  1.10.6
  1.10.7
  1.10.8
  1.11.0
  1.11beta2
  1.11beta3
  1.11rc1
  1.11rc2
  1.11.1
  1.11.2
  1.11.3
  1.11.4
  1.11.5
  1.11.6
  1.11.7
  1.11.8
  1.11.9
  1.11.10
  1.11.11
  1.11.12
  1.11.13
  1.12.0
  1.12beta1
  1.12beta2
  1.12rc1
  1.12.1
  1.12.2
  1.12.3
  1.12.4
  1.12.5
  1.12.6
  1.12.7
  1.12.8
  1.12.9
  1.12.10
  1.12.11
  1.12.12
  1.12.13
  1.12.14
  1.12.15
  1.12.16
  1.12.17
  1.13.0
  1.13beta1
  1.13rc1
  1.13rc2
  1.13.1
  1.13.2
  1.13.3
  1.13.4
  1.13.5
  1.13.6
  1.13.7
  1.13.8
  1.13.9
  1.13.10
  1.13.11
  1.13.12
  1.13.13
  1.13.14
  1.13.15
  1.14.0
  1.14beta1
  1.14rc1
  1.14.1
  1.14.2
  1.14.3
  1.14.4
  1.14.5
  1.14.6
  1.14.7
  1.14.8
  1.14.9
  1.14.10
  1.14.11
  1.14.12
  1.14.13
  1.14.14
  1.14.15
  1.15.0
  1.15beta1
  1.15rc2
  1.15.1
  1.15.2
  1.15.3
  1.15.4
  1.15.5
  1.15.6
  1.15.7
  1.15.8
  1.15.9
  1.15.10
  1.15.11
  1.15.12
  1.15.13
  1.15.14
  1.15.15
  1.16.0
  1.16beta1
  1.16.1
  1.16.2
  1.16.3
  1.16.4
  1.16.5
  1.16.6
  1.16.7
  1.16.8
  1.16.9
  1.16.10
  1.16.11
  1.16.12
  1.16.13
  1.16.14
  1.16.15
  1.17.0
  1.17beta1
  1.17rc1
  1.17rc2
  1.17.1
  1.17.2
  1.17.3
  1.17.4
  1.17.5
  1.17.6
  1.17.7
  1.17.8
  1.17.9
  1.17.10
  1.17.11
  1.17.12
  1.17.13
  1.18.0
  1.18beta1
  1.18beta2
  1.18rc1
  1.18.1
  1.18.2
  1.18.3
  1.18.4
  1.18.5
  1.18.6
  1.18.7
  1.18.8
  1.18.9
  1.18.10
  1.19.0
  1.19beta1
  1.19.1
  1.19.2
  1.19.3
  1.19.4
  1.19.5
  1.20rc1
  1.20rc2
bash-4.2# 
```

**Platform (please complete the following information):**
 - OS: Amazon Linux 2 x86_64

**Additional context**
Why not build this image daily using EC2 Image Builder with latest dependencies ?

**Comment by alexpull-aws** [comment]
There is an open feature request to have this version added to AWS CodeBuild images. See linked issue: https://github.com/aws/aws-codebuild-docker-images/issues/599

**Comment by driverpt** [comment]
@alexpull-aws , can't you just daily build this container w/ updated `goenv` version?

**Comment by subinataws** [comment]
@driverpt - Thanks for the feedback and reporting that `goenv` version we have on these images are not the latest. The purpose of this GitHub repository is to provide AWS CodeBuild customers with a reference for the Dockerfile used in the service. The latest versions of these Docker images are cached on to the AMI, which is what each CodeBuild build server uses. Updating the `goenv` on the Dockerfile daily directly doesn't make it available on the AMI and we want to keep this repo consistent with the Dockerfile that we have on CodeBuild service.

Go 1.20 support will be added to the CodeBuild images, starting with Ubuntu based images around mid-April and the Amazon Linux ones by around mid-May. Please track that in https://github.com/aws/aws-codebuild-docker-images/issues/599.

**Comment by nguyengg** [comment]
For reference, this is what I do in my repo to always get the version of Go that I want regardless of whatever is in local goenv:
```
env:
  variables:
    TARGET_GOENV_VERSION: "1.20.3"

phases:
  install:
    runtime-versions:
      golang: latest
    on-failure: ABORT
    commands:
      # We want to target a very specific golang version which might already be available from the goenv repo.
      - goenv install -l | grep ${TARGET_GOENV_VERSION} || cp ${CODEBUILD_SRC_DIR}/.goenv/${TARGET_GOENV_VERSION} ${HOME}/.goenv/plugins/go-build/share/go-build/${TARGET_GOENV_VERSION}
      - goenv install -s ${TARGET_GOENV_VERSION}
      - goenv global ${TARGET_GOENV_VERSION}
      - go version
```

Make sure to download the corresponding file from https://github.com/syndbg/goenv/tree/master/plugins/go-build/share/go-build into `.goenv/` of your repo.
