### ISSUE TITLE
Add support for Node 20

### ISSUE THREAD

**Issue by joshlang** [aws/aws-codebuild-docker-images#631]
Hello there 👋 ,

Now that Node 20 is LTS (https://nodejs.org/en/), can we add support for Node 20 as a supported runtime on CodeBuild?

Thanks heaps.

https://github.com/aws/aws-codebuild-docker-images/issues/580

**Comment by joshlang** [comment]
Just gettin' a headstart so maybe it'll be ready when LTS is ready (October?), rather than waiting an extra year

**Comment by pvcresin** [comment]
- https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-976470059

As per the above comment, I was using `aws/codebuild/standard:7.0` and the command below worked for me.

```yml
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - n 20
```
