### ISSUE TITLE
Unable to start docker in custom image

### ISSUE THREAD

**Issue by sridhar562345** [aws/aws-codebuild-docker-images#634]
I am using custom image based on `FROM public.ecr.aws/docker/library/ubuntu:22.04`
Used the following commands in buildspec.yml
```yaml
version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
```

Error logs:
```
time="2023-05-12T09:32:28.317118603Z" level=info msg="loading plugin \"io.containerd.internal.v1.tracing\"..." type=io.containerd.internal.v1
time="2023-05-12T09:32:28.317137434Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
time="2023-05-12T09:32:28.317972857Z" level=info msg=serving... address=/var/run/docker/containerd/containerd-debug.sock
time="2023-05-12T09:32:28.318030677Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock.ttrpc
time="2023-05-12T09:32:28.318070167Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock
time="2023-05-12T09:32:28.318084977Z" level=info msg="containerd successfully booted in 0.040411s"
time="2023-05-12T09:32:28.343390232Z" level=info msg="[graphdriver] trying configured driver: overlay2"
time="2023-05-12T09:32:28.345922044Z" level=error msg="failed to mount overlay: invalid argument" storage-driver=overlay2
time="2023-05-12T09:32:28.346562658Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2023-05-12T09:32:28.346612478Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
failed to start daemon: error initializing graphdriver: driver not supported
```

We have two AWS accounts, the exact configuration is working in one account but not in another.
