### ISSUE TITLE
Update sam to version 1.110.0

### ISSUE THREAD

**Issue by Rodriguevb** [aws/aws-codebuild-docker-images#709]
**Describe the bug**
dotnet8 is released in AWS, but the `Amazon Linux 2023 AArch64 standard:3.0` does not support it via `sam` command.
So.. CodeBuild has a timeout on the `sam build --template-file template.yml` command.

**To Reproduce**
Use this buildspec.yml
```
version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.x
    commands:
      - sam --version
  build:
    commands:
      - dotnet build
      - sam build --template-file template.yml
```

**Expected behavior**
Current: SAM CLI, version 1.107.0
Excepted use of 1.110.0 with dotnet8 support (see changes: https://github.com/aws/aws-sam-cli/releases/tag/v1.110.0 ) 

**Platform (please complete the following information):**
 - Amazon Linux 2023 AArch64 standard:3.0
