### ISSUE TITLE
Should images ship with `docker-credential-ecr-login` pre-installed and configured?

### ISSUE THREAD

**Issue by moltar** [aws/aws-codebuild-docker-images#743]
https://github.com/awslabs/amazon-ecr-credential-helper

It seems like a massive improvement over the classic:

```sh
aws ecr get-login-password --region=foo | \
  docker login --username AWS --password-stdin repository-uri
```

**Comment by jplock** [comment]
It looks like the package is already [included](https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/5.0/Dockerfile#L39) but needs to be [configured](https://github.com/awslabs/amazon-ecr-credential-helper?tab=readme-ov-file#configuration).

**Comment by moltar** [comment]
Hm, that's interesting, because I don't see it on `aws/codebuild/standard:7.0` image:

```
#2 ERROR: error getting credentials - err: exec: "docker-credential-ecr-login": executable file not found in $PATH, out: ``
```

**Comment by xinyu-aws** [comment]
`docker-credential-ecr-login` has been pre-installed in latest version of ubuntu:7.0 image. You can configure it by adding the following commands in your buildspec:
```
phases:
  install:
    commands:
      - mkdir -p ~/.docker
      - "echo '{\"credsStore\": \"ecr-login\"}' > ~/.docker/config.json"
```

It is not pre-configured in image because configuring it would cause docker login commands to fail.
